[package]
name = "main"
version = "0.2.1"
edition = "2024"

[dependencies]
core_graphics = { path = "../core_graphics" }
core_foundation = { path = "../core_foundation" }
ax_ui = { path = "../ax_ui" }
foundation = { path = "../foundation" }
